project:
  type: website
  output-dir: ../
  preview:
    port: 4200
    browser: false

website:
  title: "Bernardo Cruz"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
      # - href: tutorials.qmd
      #   text: Tutorials

format:
  html:
    code-overflow: scroll
    highlight-style: github
    code-fold: true
    code-summary: "Show the code"
    code-line-numbers: true
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    email-obfuscation: javascript
    search: true
    links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/bernardo-freire-barboza-da-cruz/
