project:
  type: website
  output-dir: ../

website:
  title: "Bernardo Cruz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV

format:
  html:
    highlight-style: github
    code-tools: true
    code-fold: true
    code-summary: "Show the code"
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    email-obfuscation: javascript
    search: true
    links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/bernardo-freire-barboza-da-cruz/
